### ISSUE TITLE
Newlines after meta elements are missing

### ISSUE THREAD

**Issue by rsalevsky** [openSUSE/docmanager#1]
Every element which is created or edited by docmanager is in one line. So it is needed to add a line break after the elements to keep the legibility.

**Comment by mschnitzer** [comment]
xmlformat.pl should help there. (Just as suggestion if you don't have any solution yet)

**Comment by tomschr** [comment]
@mschnitzer There is already a pretty print option inside the lxml library. :-)

**Comment by mschnitzer** [comment]
@tomschr as you can see, I'm not the "Python-Guy" :P

**Comment by tomschr** [comment]
I think, this can be done with the `.tail` property. If you set it to `\n` you'll get a linebreak. However, it is a little bit more difficult to get the indentation right.

**Comment by tomschr** [comment]
One possible algorithm:
1. Get the info element (let's say, it is saved in an `info` variable).
2. Call `info.getprevious().tail.rsplit('\n')[-1]` to the get the indentation of the `<info>` element.
3. Apply the result from (2) to DocManager's `<docmanager>` element(s).

**Comment by mschnitzer** [comment]
Should I implement that?

**Comment by tomschr** [comment]
@mschnitzer Yes, please! :-)

Having all of DocManager's elements in one line is inconvenient: it makes diffs almost useless and it is hard to read.

As such, we need to separate all the child elements from the `<docmanager>` element. Each property should rest on a separate line. To make it simpler, try to separate the (child) elements and pretty print them later.

**Comment by mschnitzer** [comment]
@tomschr I assigned you to this bug because you already opened a new issue fix branch.

**Comment by tomschr** [comment]
Just for the sake of completness: I've took a different approach. Add all children to the `<docmanager>` element, reformat them, and **then** write the result to the file.

**Comment by mschnitzer** [comment]
@tomschr your branch is still in the branch list. Can you please merge it? https://github.com/openSUSE/docmanager/tree/feature/issue1

**Comment by tomschr** [comment]
Branch already merged in commit 6156ca7, branch deleted now.
