### ISSUE TITLE
Check values for -p/--properties with Test Case

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#18]
Properties are passed through the `-p/--properties` option. The following syntax is the same:
- `-p a=1 -p b=2`
- `-p a=1,b=2`

As the comma is the separator character, a value after `=` cannot contain a comma. Although it is rarely needed (cornercase), we should extend the syntax so this would be possible:

```
-p a='1,2',b="2,3"
```

**Comment by mschnitzer** [comment]
WIP (Test Cases)

**Comment by mschnitzer** [comment]
Implemented with: https://github.com/openSUSE/docmanager/commit/0808ebd53eeba21c5cf860c3998ae424256f6d32

But we also have to add a test case for a value with spaces. This is not yet supported by DocManager.
