### ISSUE TITLE
Delete function

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#2]
It would be nice if we have a delete function for properties.

**Comment by rsalevsky** [comment]
It's basically included just use `set` and set nothing for the property.

See: https://github.com/openSUSE/docmanager#usage

**Comment by mschnitzer** [comment]
Ah ok, thanks. I tried it with "property=" but not with "property" like you said. Yea, that was actually the mistake.

Maybe we also can add this kind of variant: "property="

Because there is also no value for this property.

**Comment by rsalevsky** [comment]
When you have time feel free to implement it.

**Comment by mschnitzer** [comment]
WIP

**Comment by mschnitzer** [comment]
Implemented with: https://github.com/openSUSE/docmanager/commit/851566202c1d3a9a07b1257ec069453807d44445
