### ISSUE TITLE
Commands for often used properties

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#24]
We should add commands for often used properties. With that we can exclude typos in property names.

**Comment by mschnitzer** [comment]
WIP

**Comment by tomschr** [comment]
Use these list:
- `--maintainer`
- `--deadline`
- `--priority`
- `--translation` (or maybe just `--trans`?)
- `--languages` (or maybe just `--lang`?)

**Comment by mschnitzer** [comment]
Implemented with: https://github.com/openSUSE/docmanager/commit/b316e5f1ff72ce214ab4c7ea7b7962ffd5923cdb

@tomschr ArgParser does automatically accept shortcuts.
