### ISSUE TITLE
Adding subcommand "init"

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#26]
We need an "init" subcommand for the general initialization of a DocBook 5 document.

That means: Create a default set up with predefined properties.

**Comment by mschnitzer** [comment]
WIP

**Comment by tomschr** [comment]
Default behaviour of the `init` subcommand:
-  Should set the standard properties `status`, `maintainer`, `status`, `deadline`, `priority`, `translation`, `languages` with default values:
  - `status=editing`
  - `translation=False`
  - `priority=9`
  - `languages=en`
  - `deadline=`
  - `maintainer=`
- If needed, you can specify other values by using the specific options `--status`, `--maintainer`, `--status`, `--deadline`, `--priority`, `--translation`, `--languages`
- Contains the two options (mutually exclusive):
  - `--overwrite` replaces any existing DocManager elements with empty values
  - `--add-missing` adds missing DocManager elements to the existing set

Actually, `init` can implemented like this:
- Define our standard properties
- Check, if an `info` element exists. If not, create one
- Check, if one of the standard properties are already set:
  - If yes, skip unless we have set `--overwrite`
  - If no, add the property into the `docmanager` element
- Output/write XML
