### ISSUE TITLE
Adapt DocManager with Configuration File

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#27]
As more and more ideas and wishes are implemented, the need to have a configuration is also more and more important. A configuration file could be used to define aliases or standard options, for example.

The DocManager configuration file can be searched in these places:
- `/etc/docmanger3.config` (as a global file; do we need that?)
- `~/.config/docmanager3/config` (as a user configuration)
- `.dm3.config` (in the current SVN/Git repository)

Preferred module is [configparser](https://docs.python.org/3/library/configparser.html#module-configparser).

**Comment by mschnitzer** [comment]
The user home config file will be now created if it's not exists: https://github.com/openSUSE/docmanager/commit/1288956f2e20ac14a5ecd38595c9267b818cdec4

We can improve it later after the 3.0 release.

**Comment by tomschr** [comment]
Excellent! :+1:

**Comment by mschnitzer** [comment]
@tomschr Do we really need a global config file and a config file for each repository? I'm not against it but we should decide it for the next release.

**Comment by tomschr** [comment]
> Do we really need a global config file and a config file for each repository? I'm not against it but we should decide it for the next release.

Actually, this is a no brainer for us, very easy to implement. :smiley: 

If we want it, we can pass a list of config filenames to the [ConfigParser.read](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read) method. Filenames which cannot be found or opened are silently ignored. All configuration parameters are merged.

**Comment by tomschr** [comment]
To find the config file in current Git repository, use:

```
git rev-parse --show-toplevel
```

**Comment by tomschr** [comment]
Possible things to store in a config file:
- switch on/off colorizing
- aliases
