### ISSUE TITLE
Introduce Consistency Checks

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#30]
Our standard properties (like "status", "deadline", etc.) should contain specific datatypes which are checked when we set it:
- `deadline`: date, in the format `YYYY-MM-DD`
- `maintainer`: any non-empty string
- `priority`: any integer value with 1 as highest,
- `translation`: boolean, `True` or `False`
- `status`: one of `editing`, `edited`, `proofing`, `proofed`, `comment`, or `ready`
- `languages`: any ISO standard like `en_US`, `en`, `en,de` etc.

**Comment by mschnitzer** [comment]
WIP
