### ISSUE TITLE
Remove Action class

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#34]
The `Action` class from `action.py` is useless as it doesn't really improve code quality.  One (better?) implementation avoids this class and uses just a function, see the [feature/issue23](https://github.com/openSUSE/docmanager/blob/feature/issue23/docmanager/__init__.py) branch.

**Comment by mschnitzer** [comment]
I would say this can be seen as a part of our planned "refactoring-update" after 3.0 has been released, right? I don't think milestone 3.0 is a good choice for that.

@tomschr What do you mean?

**Comment by tomschr** [comment]
Yes, as this is no blocker bug, I'd say this can be done for the 3.1 milestone.

**Comment by mschnitzer** [comment]
As we discussed it again, we came to the solution that we don't want to remove the "Actions" class. What we removed is the "Files" class in filehandler.py. This is done in https://github.com/openSUSE/docmanager/commit/6b80961c1fea2645d9558102709e6267ead61a16
