### ISSUE TITLE
Extend `init` Subcommand to Allow Default Options

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#35]
Currently, the `init` subcommand can only set the default properties to some default values. If you would like to set only one (or two) properties to different values, you have to run `docmanager` twice:

``` shell
$ docmanager init *.xml
$ docmanager set --maintainer tux *.xml
```

As a convenience, it would be nice to make the initialization part a little bit more user-friendly and allow this as well:

``` shell
$ docmanager init --maintainer tux *.xml
```

Does that make sense?

**Comment by mschnitzer** [comment]
Makes sense.

**Comment by mschnitzer** [comment]
WIP
