### ISSUE TITLE
DocManager doesn't check for DocBook5 Elements

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#37]
At the moment, DM doesn't check if the start tag belongs to the DocBook 5 namespace.

Preferred solution:
1. Check what the namespace of the root element is.
2. If namespace is DocBook 5 continue. If not, abort with an error message.

**Comment by mschnitzer** [comment]
Implemented with https://github.com/openSUSE/docmanager/commit/93f8299cd537c6f0a1dedb043b02066fb32693c7
