### ISSUE TITLE
Add Missing Docstring for Functions

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#45]
These functions don't have a docstring:
-  `input_format_check` in `docmanager/__init__.py`
- `logmgr_flog` in `documentation/logmanager.py`
- `init_default_props` in `documentation/xmlhandler.py`
- the whole `Handler` class and its methods in `docmanager/xmlutil.py`

**Comment by mschnitzer** [comment]
I've documented my functions in https://github.com/openSUSE/docmanager/commit/282749d7eb28127ba01bb203a743aa0114addfe0

Can you please document your functions? Thanks!

**Comment by mschnitzer** [comment]
Can be closed now. Thanks Thomas for providing your documentation!
