### ISSUE TITLE
Implement Query/Analyze Feature

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#49]
The current syntax is a bit strange. We would like to have a more compact syntax. 

Let's say, we would like to have all files with have the following conditions:
- maintainer who is tux or wilber,
- in status edited,
- but not with priority 2

The following are possible options:
1. With `--include`/`-I` and `--exclude`/`-E` options (this was how DM2 did it)
   
   ```
   --include "maintainer=tux,wilber" --include "status=edited" --exclude "priority=2"
   ```
2. With `--query`/`-q` (as one quoted string)
   
   ```
   -q "maintainer=tux,wilber;status=edited;-priority=2"
   ```
3. With our standard options like `--maintainer`/`-M`
   
   ```
   --maintainer tux,wilber --status edited --not-priority 2
   ```

Which one should we prefer?

**Comment by tomschr** [comment]
![analyze-plan](https://cloud.githubusercontent.com/assets/1312925/8851337/2fb600f8-314f-11e5-8083-07e2afb7f4c7.jpg)

**Comment by tomschr** [comment]
![analyze-plan](https://cloud.githubusercontent.com/assets/1312925/8851609/dbf77ce2-3150-11e5-8650-a48ccf868cb2.jpg)

**Comment by tomschr** [comment]
### Frank's Solution

Ok, after discussing with Frank, we found a fourth solution. The `query`/`analyze` subcommand is divided into two passes:

**First pass (retrieving):**
- The option `--filter`/`-F` passes a single statement (like `maintainer=tux`)
- The option `-F` can be used many times
- The argument for `-F` has the syntax:
  `
  [+|-]PROPERTY=VALUE
  `
- Additionally, a `--sort=[+|-]PROPERTY` option can be used to sort it against a given property. The direction is set by `+` or `-`: `+` means ascending sort order, `-` means descending sort order

**Second pass (output formatting)**:

The output can be influenced with the `-q`/`--queryformat`. The querystring has the following properties:
- Each placeholder is written between `{` and `}`, for example `{maintainer}`
- Anything else is written to the output as it is.

For example:

```
--queryformat "{filename} {maintainer} [{deadline}]\n"
```

The placeholders are in curely brackets which are replaced during output. A good(?) idea is to use syntax from the format specification used by the `.format` method.

See 
- https://docs.python.org/3/library/string.html#formatspec
- http://pyformat.info/

### Examples
1.  Return all files which are maintained by tux and are not in status "editing":
   
   ```
   docmanager query --filter "maintainer=tux" --filter "-status=editing"
   ```
2. Same as (1), but sort it in descending filename order:
   
   ```
   docmanager query --filter "maintainer=tux" --filter "-status=editing" --sort="-filename"
   ```

**Comment by mschnitzer** [comment]
OK, I added the feature in https://github.com/openSUSE/docmanager/commit/de13116d96b32b965970b9c316bc446152ab0d96.

That is still missing:
- Update man page
- Update --help
- Implement default query support (in combination with our config files, see issue #27)

**Comment by mschnitzer** [comment]
Fully implemented
