### ISSUE TITLE
Use logging module

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#5]
It might be a good idea to add a logging module to the project.

**Comment by tomschr** [comment]
It's a little bit tricky to figure out all the relevant things for logging. To initialize the `logging` module, I usually use this code:

``` python
import logging

log = logging.getLogger(__file__)
ch = logging.StreamHandler(sys.stderr)
frmt = logging.Formatter('%(levelname)s: %(message)s')
ch.setFormatter(frmt)
log.setLevel(logging.DEBUG)
log.addHandler(ch)
```

Additionally, add a `-v`/`--verbose` option with `action="count"`:

``` python
parser.add_argument('-v', '--verbose',
        action='count',
        help="Increase verbosity level"
        )
```

To set the log level accordingly:

``` python
loglevel = {None: logging.NOTSET,
                # 1:logging.CRITICAL,
                # 2:logging.ERROR,
                # 1:logging.WARNING,
                1:logging.INFO,
                2:logging.DEBUG,
               }
args=parser.parse_args()
log.setLevel(loglevel.get(args.verbose, logging.DEBUG))
```

Use `log.debug()` and the other functions as usual.

**Comment by mschnitzer** [comment]
Implemented with: https://github.com/openSUSE/docmanager/commit/856175f66201734588022676eab118e37b097a9b

**Comment by tomschr** [comment]
@mschnitzer You've forgot to push the file `logmanager.py`. I've tried to recover it, but the `logmgr_flog()` function needs special dedication from you. :-) Please implement them from your working copy.

**Comment by mschnitzer** [comment]
Added by https://github.com/openSUSE/docmanager/commit/6d4f9273277fa742fca18b3b245e7f075e51ecae
