### ISSUE TITLE
Proceed on error when handling multiple files

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docmanager#50]
When running docmanager on multiple files it will stop processing when an error occurs with one of the files. After that it's up to the user to find out which files have been changed and which ones not.

docmanager should continue processing files when an error occurs:
- print an error message to STDERR and continue with the next file
- having finished, print a summary telling the users how many files were successfully changed and how many files errored

If at all, the current behaviour should only be available on request, e.g. with a `--stop-on-error` switch.

**Comment by mschnitzer** [comment]
Implemented with https://github.com/openSUSE/docmanager/commit/db2e26c04499b1b70d772ab1c1a5e171dede3452
