### ISSUE TITLE
Include filename in error messages

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docmanager#51]
This is not helpful:

```
> docmanager init *.xml
15:01:42 [ERROR]: Cannot add info element to appendix. Not a valid root element.
```

since I do not know in which file the error occured.

**Comment by mschnitzer** [comment]
appendix has been added to the valid root element list in https://github.com/openSUSE/docmanager/commit/c0f750baa0212d66e334db68fe2f78e3979adcb0

To the main problem: I will work on that.

**Comment by mschnitzer** [comment]
Fixed in https://github.com/openSUSE/docmanager/commit/155bb007f357ac2a2d16050526c90e4c0e6d7635
