### ISSUE TITLE
Default property for product or release is missing

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docmanager#53]
We need to add another default property for the product or release (to determine e.g. between SLES and SLED). In svn this property was called `doc:release`, but maybe we can find a better name...

**Comment by tomschr** [comment]
@fsundermeyer "release" should be fine. :)

@mschnitzer Could you add "release" into DefaultDocManagerProperties (file `docmanager/core.py`) and extend/test with our test case?

**Comment by mschnitzer** [comment]
WIP

**Comment by mschnitzer** [comment]
Implemented in https://github.com/openSUSE/docmanager/commit/0956c43330b98732088969ddfd92501bae3794bf
