### ISSUE TITLE
usage output irritating

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docmanager#54]
The output of

```
> docmanager get --help
usage: docmanager COMMAND [OPTIONS] FILE [FILE ...] get [-h] [-p PROPERTIES]
                                                        [-f {table,json}]
                                                        FILE [FILE ...]
```

is not only strangely formatted, but also has one "FILE [FILE ...]" to much. Suggested correction:

```
General usage:  docmanager COMMAND [OPTIONS] FILE [FILE ...]
docmanager get: docmanager get [-p PROPERTIES]  [-f {table,json}] FILE [FILE ...]
```

Also applies to all other subcommands.

**Comment by tomschr** [comment]
@fsundermeyer Thanks Frank for the report!

I'm not sure if it is possible to add your "general usage" line into our [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) parser. The closest what we can get is this:

```
$ docmanager -h
usage: docmanager [-h] [--version] [-v] [--langlist]
                  {init,i,get,g,set,s,del,d,query,q,analyze} ...
```

and with a subcommand:

```
$ docmanager get -h
usage: docmanager get [-h] [-p PROPERTIES] [-f {table,json}] FILE [FILE ...]
```

**Comment by fsundermeyer** [comment]
tomschr: Your suggested solution looks fine to me!

**Comment by mschnitzer** [comment]
As discussed with @tomschr, we can close it here.
