### ISSUE TITLE
Add Tracker Meta Information

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#56]
## Current Situation

Our related sister project openSUSE/suse-xsl needs to extend the JavaScript code (see related  issue openSUSE/suse-xsl#36).
At the moment, there is hard-coded information about the Bugzilla product. This is unfortunate as products will very likely change in the future.

The better solution is to move this information (and other tracker information) into the XML sources. To  handle such tracker information more easily, DocManager should support that.
## Suggested Solutions

DocManager should be able to store tracker information for Bugzilla & GitHub in the `<dm:docmanager>` element. Three approaches should be considered:
1. Nested structure
   DM should use `<trackerinfo>` and use child elements to store its information.
   Pros:
   - Better readability
   - shorter tag names
   
   Cons
   - Not compatible with current implementation
2. Flat structure
   Every information should map to an element name with a prefix `tracker-`.
   Pros:
   - Easy to implement
   
   Cons
   - Worse readability
3. DocBook elements
   We could use `releaseinfo` to store at least some information. However, it is not really a good option as the semantics are not very appropriate.

**Comment by tomschr** [comment]
We've decided to use number 1 with the following structure/tags:

``` xml
<dm:bugtracker>
   <url><!-- Tracker URL --></url>
  <component><!-- Bugzilla component --></component>
  <product><!-- Bugzilla tracker product --></product>
  <assignee><!-- Name of assignee --></assignee>
  <version><!-- version --></version>
</dm:bugtracker>
```
- `bugtracker`: common parent element for all bug tracker related issues
- `url`: tracker URL
  - For Bugzilla, for example: https://bugzilla.suse.com/enter_bug.cgi
  - For GitHub, for example: https://github.com/openSUSE/suse-xsl/issues/new
- `component`: Bugzilla component, usually `Documentation` by default; not used for GitHub
- `product`: Bugzilla product, for example `SUSE Cloud 4`; not used for GitHub
- `assignee`: Account name, login, or otherwise of the assignee
- `version`: version of the product or release

**Comment by mschnitzer** [comment]
We also have to update the man page.

**Comment by mschnitzer** [comment]
man page has been updated: https://github.com/openSUSE/docmanager/commit/ae221a69d40fc6e34518cc71f9a340ca0372df74
