### ISSUE TITLE
Support Aliases

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#64]
Aliases can be very useful to collect specific options and parameters into one. This is related to issue #27.

This issue is just a reminder. The complete issue has to be definied.

**Comment by mschnitzer** [comment]
WIP

**Comment by mschnitzer** [comment]
1. aliases are located in the [alias] section of the config files.
2. we have to parse the config file before we parse other arguments (maybe a separate argparser is needed here)
3. then we have to check if the user want to use an alias (index 1 in sys.argv)
4. if three is `true`, we must manipulate sys.argv and rewrite the arguments

@tomschr are you ok with that? Feel free to adjust some things.

**Comment by tomschr** [comment]
@mschnitzer Looks good to me.
