### ISSUE TITLE
Implement 'config' sub command

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#70]
We need a 'config' sub command for editing the config files.

**Comment by mschnitzer** [comment]
WIP

**Comment by mschnitzer** [comment]
The feature is now implemented but we need test cases.

**Comment by tomschr** [comment]
Should we allow a `-f` option to use a given config file?

**Comment by mschnitzer** [comment]
@tomschr https://github.com/openSUSE/docmanager/commit/b0274094d86299710d28bf1404d6045ddd8b6b0e#diff-5c7865f277cfe749c0ba7a26409e1d74R223
