### ISSUE TITLE
Implement 'alias' sub command

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#72]
We need a sub command for modify the 'alias' section in config files.

**Comment by tomschr** [comment]
We agreed on `config` instead of `alias`, similar to `git config`. Changed title accordingly.

**Comment by tomschr** [comment]
@mschnitzer What is the difference between issue #70?

**Comment by mschnitzer** [comment]
The difference is: There are only options to modify the aliases. It's shorter and we can offer the possibility to list all aliases and some other functions.

**Comment by mschnitzer** [comment]
WIP
