### ISSUE TITLE
Multiprocessing Feature

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#75]
It would be nice to have a multiprocessing feature.

**Comment by tomschr** [comment]
Useful links:
- https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing
- https://docs.python.org/3/library/concurrency.html
- https://cslocumwx.github.io/blog/2015/02/23/python-multiprocessing/

As far as I know, for Python3 the `concurrency` module should be the preferred way.

**Comment by tomschr** [comment]
Another useful feature: adding a global `-j`/`--jobs` option. The `make` tool has this feature too and it is described like this:

```
-j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
```

When no `-j` option is given, DM executes its task in a sequential order (no change). If the user passes `-j 4`, DM will distribute its work on four cores.

**Comment by mschnitzer** [comment]
https://github.com/openSUSE/docmanager/commit/c2ed9629d9c65a593d6c22de9ae1f3a90f973577
