### ISSUE TITLE
Fix some code smells

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#85]
https://landscape.io/github/openSUSE/docmanager/203
https://scrutinizer-ci.com/g/openSUSE/docmanager/?branch=develop

**Comment by tomschr** [comment]
For completeness: use `flake8` (can be installed through `pip install flake8`). See https://flake8.readthedocs.org/en/ for more information.

We should add settings for `flake8` into `setup.cfg` file like this:

``` ini
[flake8]
max-line-length = 90
exclude = tests/*,*/migrations/*,*/south_migrations/*
```
