### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docmanager#91]
DM should be optimized to make it run faster.

One idea is to create profiling information like described in the "Python Profilers" chapter:
https://docs.python.org/3.4/library/profile.html#the-python-profilers

Other helpful resources:
- [`timeit`](https://docs.python.org/3.4/library/timeit.html) module
- [`trace`](https://docs.python.org/3.4/library/trace.html) module

**Comment by mschnitzer** [comment]
https://github.com/openSUSE/docmanager/commit/c2ed9629d9c65a593d6c22de9ae1f3a90f973577
